export const cities = [
  "All",
  "Ahmedabad",
  "Bengaluru",
  "Bhopal",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Delhi",
  "Gurgaon",
  "Hyderabad",
  "Indore",
  "Jaipur",
  "Kolkata",
  "Lucknow",
  "Mumbai",
  "Nagpur",
  "Noida",
  "Patna",
  "Pune",
  "Surat"
];

export const nichesArray = [
  "All",
  "Artificial Intelligence",
  "Big Data",
  "Blockchain",
  "Cloud Computing",
  "Cybersecurity",
  "Data Science",
  "Database Administration",
  "DevOps",
  "Game Development",
  "IT Consulting",
  "IT Project Management",
  "IT Support and Helpdesk",
  "IoT (Internet of Things)",
  "Machine Learning",
  "Mobile App Development",
  "Network Administration",
  "Software Development",
  "Systems Administration",
  "UI/UX Design",
  "Web Development"
];
